### PR TITLE
Datatypes

### PR DESCRIPTION
**Pull request by bertfrees**
See https://github.com/snaekobbi/pipeline-mod-mtm/issues/4

Please don't merge yet.

@joeha480 I've given Ammar push access to this repo so that he can play around with the datatypes a bit. Feel free to restrict access again later.

@usama49 I've committed an example datatype (`mtm:line-spacing`) and also added a test. In order to run this you need https://github.com/daisy/pipeline-framework/pull/97 and https://github.com/daisy/pipeline-build-utils/pull/18.

### CODE REVIEW

**Comment by bertfrees** [comment]
@josteinaj In order to test this with the web UI, it's maybe easiest to just drop the snapshots of mod-mtm, framework-core, webservice and webservice-utils in the system folder of a pipeline server instance.

**Comment by josteinaj** [comment]
@bertfrees Ok, sounds reasonable. I'm currently trying to pinpoint a problem with webservice and/or webservice-utils though. The master branch of pipeline-framework doesn't work. That is, the Web API doesn't respond when building the newest assembly (v1.9.7) with the newest framework (1.10.0-SNAPSHOT).

**Comment by bertfrees** [comment]
OK. I was thinking about how to test this including the webservice. Something along the lines of what Javi did here: https://github.com/daisy/pipeline-it/tree/master/daisy/framework-integration/src/test/java/org/daisy/integration. Maybe I'll refactor it a bit someday so that it can be used from any JUnit test (with Pax Exam) with any modules included. (Currently it relies on building and running the assembly.)

**Comment by josteinaj** [comment]
@bertfrees so @usama49 can just commit to this PR, right?

**Comment by bertfrees** [comment]
Yes.

**Pull request closed without merging**
